name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        submodules: true
        lfs: true
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.0.0
      with:
        dotnet-version: '2.2.103' # SDK Version to use.
    - name: Install Powershell
      run: sudo apt-get install -y powershell
    - name: Install Android NDK
      env:
        ndkname: android-ndk-r20
      run: |
        wget -q -O ndk.zip https://dl.google.com/android/repository/${ndkname}-linux-x86_64.zip
        unzip -q ndk.zip
        mv ${ndkname} ndk
        cd ndk
        pwd > ${GITHUB_WORKSPACE}/ndkpath.txt
    - name: Build
      run: |
        cd ${GITHUB_WORKSPACE}
        pwsh -Command ./build.ps1
